import { AFRICA_COUNTRY_CODES } from "./africa.js";

/** Known country names only. Unknown names stay unresolved rather than guessed. */
export const COUNTRY_CODES: Record<string, string> = {
  algeria: "DZ",
  angola: "AO",
  benin: "BJ",
  botswana: "BW",
  "burkina faso": "BF",
  burundi: "BI",
  "cabo verde": "CV",
  "cape verde": "CV",
  cameroon: "CM",
  "central african republic": "CF",
  chad: "TD",
  comoros: "KM",
  congo: "CG",
  "democratic republic of the congo": "CD",
  drc: "CD",
  "cote d'ivoire": "CI",
  "côte d'ivoire": "CI",
  "ivory coast": "CI",
  djibouti: "DJ",
  egypt: "EG",
  "equatorial guinea": "GQ",
  eritrea: "ER",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  gabon: "GA",
  gambia: "GM",
  "the gambia": "GM",
  ghana: "GH",
  guinea: "GN",
  "guinea-bissau": "GW",
  kenya: "KE",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  madagascar: "MG",
  malawi: "MW",
  mali: "ML",
  mauritania: "MR",
  mauritius: "MU",
  morocco: "MA",
  mozambique: "MZ",
  namibia: "NA",
  niger: "NE",
  nigeria: "NG",
  rwanda: "RW",
  "sao tome and principe": "ST",
  senegal: "SN",
  seychelles: "SC",
  "sierra leone": "SL",
  somalia: "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  sudan: "SD",
  tanzania: "TZ",
  togo: "TG",
  tunisia: "TN",
  uganda: "UG",
  zambia: "ZM",
  zimbabwe: "ZW",
  "western sahara": "EH",
  india: "IN",
  bangladesh: "BD",
  "united states": "US",
  usa: "US",
  "united states of america": "US",
  "united kingdom": "GB",
  uk: "GB",
  france: "FR",
  germany: "DE",
  netherlands: "NL",
  brazil: "BR",
  mexico: "MX",
  canada: "CA",
  australia: "AU",
  china: "CN",
  japan: "JP",
  uae: "AE",
  "united arab emirates": "AE",
  singapore: "SG",
  indonesia: "ID",
  vietnam: "VN",
  philippines: "PH",
  poland: "PL",
  romania: "RO",
  ukraine: "UA",
  colombia: "CO",
  ecuador: "EC",
  chile: "CL",
  argentina: "AR",
  peru: "PE",
  bolivia: "BO",
  paraguay: "PY",
  uruguay: "UY",
  venezuela: "VE",
  guatemala: "GT",
  honduras: "HN",
  nicaragua: "NI",
  "costa rica": "CR",
  panama: "PA",
  cuba: "CU",
  jamaica: "JM",
  haiti: "HT",
  "dominican republic": "DO",
  "el salvador": "SV",
  belize: "BZ",
  guyana: "GY",
  suriname: "SR",
  belgium: "BE",
  spain: "ES",
  italy: "IT",
  portugal: "PT",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  switzerland: "CH",
  austria: "AT",
  ireland: "IE",
  "new zealand": "NZ",
  pakistan: "PK",
  nepal: "NP",
  "sri lanka": "LK",
  thailand: "TH",
  malaysia: "MY",
  cambodia: "KH",
  laos: "LA",
  myanmar: "MM",
  "south korea": "KR",
  korea: "KR",
  taiwan: "TW",
  israel: "IL",
  jordan: "JO",
  lebanon: "LB",
  turkey: "TR",
  iran: "IR",
  iraq: "IQ",
  "saudi arabia": "SA",
  qatar: "QA",
  kuwait: "KW",
  bahrain: "BH",
  oman: "OM",
  yemen: "YE",
  kazakhstan: "KZ",
  uzbekistan: "UZ",
};

export function countryCodeFor(name: string | null | undefined): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  return COUNTRY_CODES[key] ?? null;
}

const CODE_TO_CONTINENT: Record<string, string> = {
  IN: "Asia",
  BD: "Asia",
  CN: "Asia",
  JP: "Asia",
  SG: "Asia",
  ID: "Asia",
  VN: "Asia",
  PH: "Asia",
  AE: "Middle East and North Africa",
  US: "Americas",
  BR: "Americas",
  MX: "Americas",
  CA: "Americas",
  CO: "Americas",
  CL: "Americas",
  AR: "Americas",
  PE: "Americas",
  EC: "Americas",
  BO: "Americas",
  PY: "Americas",
  UY: "Americas",
  VE: "Americas",
  GT: "Americas",
  HN: "Americas",
  NI: "Americas",
  CR: "Americas",
  PA: "Americas",
  CU: "Americas",
  JM: "Americas",
  HT: "Americas",
  DO: "Americas",
  SV: "Americas",
  BZ: "Americas",
  GY: "Americas",
  SR: "Americas",
  BE: "Europe",
  ES: "Europe",
  IT: "Europe",
  PT: "Europe",
  SE: "Europe",
  NO: "Europe",
  DK: "Europe",
  FI: "Europe",
  CH: "Europe",
  AT: "Europe",
  IE: "Europe",
  NZ: "Asia",
  PK: "Asia",
  NP: "Asia",
  LK: "Asia",
  TH: "Asia",
  MY: "Asia",
  KH: "Asia",
  LA: "Asia",
  MM: "Asia",
  KR: "Asia",
  TW: "Asia",
  IL: "Middle East and North Africa",
  JO: "Middle East and North Africa",
  LB: "Middle East and North Africa",
  TR: "Middle East and North Africa",
  IR: "Middle East and North Africa",
  IQ: "Middle East and North Africa",
  SA: "Middle East and North Africa",
  QA: "Middle East and North Africa",
  KW: "Middle East and North Africa",
  BH: "Middle East and North Africa",
  OM: "Middle East and North Africa",
  YE: "Middle East and North Africa",
  KZ: "Asia",
  UZ: "Asia",
  AU: "Asia",
  GB: "Europe",
  FR: "Europe",
  DE: "Europe",
  NL: "Europe",
  PL: "Europe",
  RO: "Europe",
  UA: "Europe",
};

for (const code of AFRICA_COUNTRY_CODES) {
  CODE_TO_CONTINENT[code] = "Africa";
}

export function continentForCountryCode(code: string | null | undefined): string | null {
  if (!code) return null;
  return CODE_TO_CONTINENT[code.trim().toUpperCase()] ?? null;
}
