import { createHtmlCatalogueAdapter } from "./html-catalogue.js";
import { hub71StartupDirectoryAdapter } from "./hub71-startup-directory.js";
import { niaInnovationCatalogueAdapter } from "./nia-innovation-catalogue.js";
import type { SourceAdapter } from "./types.js";

/** First-wave Asia html-catalogue adapters (expand after `asia:verify` + dry-run). */
export const asiaAdapters: SourceAdapter[] = [
  createHtmlCatalogueAdapter({
    id: "j-startup",
    siteOrigin: "https://www.j-startup.go.jp",
    pathPattern: /^\/en\/startups\/[^/]+\.html$/i,
    extraListingUrls: ["https://www.j-startup.go.jp/en/startups/"],
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "j-startup-impact",
    siteOrigin: "https://www.j-startup.go.jp",
    pathPattern: /^\/en\/startups\/[^/]+\.html$/i,
    extraListingUrls: ["https://www.j-startup.go.jp/en/startups/"],
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "sginnovate-portfolio",
    siteOrigin: "https://www.sginnovate.com",
    pathPattern: /^\/our-portfolio\/[^/]+\/?$/i,
    extraListingUrls: [
      "https://www.sginnovate.com/full-portfolio",
      "https://www.sginnovate.com/our-portfolio",
    ],
    htmlUrlPattern: /https:\/\/www\.sginnovate\.com\/our-portfolio\/[a-z0-9-]+(?:\?[^"'\s]*)?/gi,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  hub71StartupDirectoryAdapter,
  createHtmlCatalogueAdapter({
    id: "open-innovation-network-singapore",
    siteOrigin: "https://www.openinnovationnetwork.gov.sg",
    pathPattern: /^\/success-stories\/success-stories\/.+/i,
    extraListingUrls: [
      "https://www.openinnovationnetwork.gov.sg/success-stories/success-stories",
    ],
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "accelerating-asia",
    siteOrigin: "https://www.acceleratingasia.com",
    pathPattern: /^\/portfolio\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "wavemaker-partners-portfolio",
    siteOrigin: "https://wavemaker.vc",
    pathPattern: /^\/portfolio\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "wavemaker-impact-portfolio",
    siteOrigin: "https://wavemakerimpact.com",
    pathPattern: /^\/portfolio\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "circulate-capital",
    siteOrigin: "https://www.circulatecapital.com",
    pathPattern: /^\/company\/[^/]+\/?$/i,
    extraListingUrls: ["https://www.circulatecapital.com/companies/"],
    sitemap: {
      url: "https://www.circulatecapital.com/companies_pt-sitemap.xml",
      locPathPattern: /^\/company\/[^/]+\/?$/i,
    },
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "hkstp-company-directory",
    siteOrigin: "https://www.hkstp.org",
    pathPattern: /^\/en\/directory\/[^/]+\/[^/]+\/?$/i,
    extraListingUrls: ["https://www.hkstp.org/en/directory"],
    excludePathPattern: /^\/en\/(discover|programmes|insights|news)(\/|$)/i,
    sitemap: {
      url: "https://www.hkstp.org/sitemap.xml",
      followSitemapIndex: true,
      locPathPattern: /^\/en\/directory\/[^/]+\/[^/]+\/?$/i,
    },
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "insignia-ventures-partners",
    siteOrigin: "https://www.insignia.vc",
    pathPattern: /^\/(portfolio|companies)\/[^/]+\/?$/i,
    extraListingUrls: ["https://www.insignia.vc/companies", "https://www.insignia.vc/portfolio"],
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "thinkzone-ventures",
    siteOrigin: "https://thinkzone.vc",
    pathPattern: /^\/portfolio\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "iterative-demo-day",
    siteOrigin: "https://www.iterative.vc",
    pathPattern: /^\/companies\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "appworks-accelerator",
    siteOrigin: "https://appworks.tw",
    pathPattern: /^\/portfolio\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "kaust-scalex-portfolio",
    siteOrigin: "https://entrepreneurship.kaust.edu.sa",
    pathPattern: /^\/portfolio\/scalex\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  niaInnovationCatalogueAdapter,
  createHtmlCatalogueAdapter({
    id: "hkust-entrepreneurship-center",
    siteOrigin: "https://ec.hkust.edu.hk",
    pathPattern: /^\/node\/\d+$/i,
    extraListingUrls: ["https://ec.hkust.edu.hk/startup-alumni"],
    excludePathPattern: /^\/(events?|about-us|one-million|unicorn-day|ec-team|ipic)(\/|$)/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
];
