import { createHtmlCatalogueAdapter } from "./html-catalogue.js";
import type { SourceAdapter } from "./types.js";

const EARTHSHOT_YEAR = /^\/winners-finalists\/\d{4}\/?$/;

export const catalogueAdapters: SourceAdapter[] = [
  createHtmlCatalogueAdapter({
    id: "earthshot-prize",
    siteOrigin: "https://earthshotprize.org",
    pathPattern: /^\/winners-finalists\/[^/]+\/?$/i,
    excludePathPattern: /^\/winners-finalists\/(all|\d{4})\/?$/i,
    followListingPathPattern: EARTHSHOT_YEAR,
    resourceType: "SOLUTION",
    evidenceBasis: "PROGRAMME_SELECTED",
    titleSuffixStrip: /\s*\|\s*The Earthshot Prize.*$/i,
  }),
  createHtmlCatalogueAdapter({
    id: "hundred",
    siteOrigin: "https://hundred.org",
    pathPattern: /^\/en\/innovations\/[^/]+\/?$/i,
    excludePathPattern: /^\/en\/innovations\/(new|filters)\/?$/i,
    sitemap: { url: "https://hundred.org/sitemaps/innovations.xml" },
    resourceType: "SOLUTION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "oecd-opsi",
    siteOrigin: "https://oecd-opsi.org",
    pathPattern: /^\/innovations\/[^/]+\/?$/i,
    wordpressRest: { origin: "https://oecd-opsi.org", postType: "case" },
    resourceType: "CASE_STUDY",
    evidenceBasis: "INDEPENDENT_ASSESSMENT",
  }),
  createHtmlCatalogueAdapter({
    id: "skoll",
    siteOrigin: "https://skoll.org",
    pathPattern: /^\/grantee\/[^/]+\/?$/i,
    wordpressRest: { origin: "https://skoll.org", postType: "grantees" },
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "echoing-green",
    siteOrigin: "https://echoinggreen.org",
    pathPattern: /^\/issues\/[^/]+\/?$/i,
    resourceType: "PROGRAMME",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "elevate-prize",
    siteOrigin: "https://elevateprize.org",
    pathPattern: /^\/winner\/[^/]+\/?$/i,
    htmlUrlPattern: /https:\/\/elevateprize\.org\/winner\/[a-z0-9-]+(?:\?[^"'\s]*)?/gi,
    resourceType: "PERSON",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "audacious-project",
    siteOrigin: "https://www.audaciousproject.org",
    pathPattern: /^\/grantees\/[^/]+\/?$/i,
    resourceType: "PROJECT",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "holcim-foundation",
    siteOrigin: "https://www.holcimfoundation.org",
    pathPattern: /^\/projects\/[^/]+\/?$/i,
    resourceType: "PROJECT",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "mulago",
    siteOrigin: "https://www.mulagofoundation.org",
    pathPattern: /^\/portfolio\/[^/]+\/?$/i,
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "draper-richards-kaplan",
    siteOrigin: "https://www.drkfoundation.org",
    pathPattern: /^\/organization\/[^/]+\/?$/i,
    wordpressRest: { origin: "https://www.drkfoundation.org", postType: "portfolios" },
    resourceType: "ORGANISATION",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "elrha",
    siteOrigin: "https://www.elrha.org",
    pathPattern: /^\/projects\/[^/]+\/?$/i,
    resourceType: "PROJECT",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "eit-food",
    siteOrigin: "https://www.eitfood.eu",
    pathPattern: /^\/(entrepreneurship|missions)\/[^/]+\/?$/i,
    resourceType: "PROGRAMME",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "nesta",
    siteOrigin: "https://www.nesta.org.uk",
    pathPattern: /^\/project\/[^/]+\/?$/i,
    resourceType: "PROJECT",
    evidenceBasis: "INDEPENDENT_ASSESSMENT",
  }),
  createHtmlCatalogueAdapter({
    id: "apolitical",
    siteOrigin: "https://apolitical.co",
    pathPattern: /^\/(en\/)?articles\/[^/]+\/?$/i,
    excludePathPattern: /^\/(en\/)?articles\/new\/?$/i,
    resourceType: "CASE_STUDY",
    evidenceBasis: "EDITORIALLY_CURATED",
  }),
  createHtmlCatalogueAdapter({
    id: "global-resilience-partnership",
    siteOrigin: "https://www.globalresiliencepartnership.org",
    pathPattern: /^\/resource\/[^/]+\/?$/i,
    followListingPathPattern: /^\/resources\/page\/\d+\/?$/i,
    maxListingPages: 30,
    resourceType: "RESEARCH",
    evidenceBasis: "INDEPENDENT_ASSESSMENT",
  }),
  createHtmlCatalogueAdapter({
    id: "zayed-sustainability-prize",
    siteOrigin: "https://zayedsustainabilityprize.com",
    pathPattern: /^\/en\/impacts\/impacts-stories\/[^/]+\/?$/i,
    sitemap: { url: "https://zayedsustainabilityprize.com/sitemap.xml" },
    resourceType: "PROJECT",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
  createHtmlCatalogueAdapter({
    id: "global-good-fund",
    siteOrigin: "https://globalgoodfund.org",
    pathPattern: /^\/entrepreneurs\/\d{4}-fellows\/?$/i,
    sitemap: {
      url: "https://globalgoodfund.org/page-sitemap.xml",
      locPathPattern: /\/entrepreneurs\/\d{4}-fellows\/?$/i,
    },
    resourceType: "PROGRAMME",
    evidenceBasis: "PROGRAMME_SELECTED",
  }),
];
